services:
  new-pro:
    image: ghcr.io/lei-rr/new-pro:latest
    container_name: new-pro
    restart: always
    ports:
      - "${PORT:-3033}:${PORT:-3033}"
    env_file:
      - .env
    networks:
      - new-api_network

networks:
  new-api_network:
    external: true
    name: new-api_default
