import type { Component } from 'vue';
import {
  LayoutDashboard,
  ScrollText,
  Boxes,
  CircleDollarSign,
  Bell,
  Sun,
  Moon,
  Menu,
  X,
  Search,
  Filter,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ArrowUpRight,
  ArrowDownRight,
  RefreshCw,
  Activity,
  Cpu,
  Users,
  KeyRound,
  Globe,
  Layers,
  Clock,
  AlertTriangle,
  CircleAlert,
  Info,
  Zap,
  Database,
  Eye,
  Gauge,
  Coins,
  TrendingUp,
  Sparkles,
  Wifi,
  WifiOff,
  type LucideIcon,
} from '@lucide/vue';

/** 全局图标注册表：视图层只从这里引用，保证图标一致性 */
export const Icons = {
  nav: {
    dashboard: LayoutDashboard,
    logs: ScrollText,
    dimensions: Boxes,
    cost: CircleDollarSign,
    alerts: Bell,
  } satisfies Record<string, Component | LucideIcon>,
  ui: {
    sun: Sun,
    moon: Moon,
    menu: Menu,
    close: X,
    search: Search,
    filter: Filter,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronDown: ChevronDown,
    arrowUpRight: ArrowUpRight,
    arrowDownRight: ArrowDownRight,
    refresh: RefreshCw,
    activity: Activity,
    cpu: Cpu,
    users: Users,
    key: KeyRound,
    globe: Globe,
    layers: Layers,
    clock: Clock,
    alertTriangle: AlertTriangle,
    circleAlert: CircleAlert,
    info: Info,
    zap: Zap,
    database: Database,
    eye: Eye,
    gauge: Gauge,
    coins: Coins,
    trendingUp: TrendingUp,
    sparkles: Sparkles,
    wifi: Wifi,
    wifiOff: WifiOff,
  } satisfies Record<string, Component | LucideIcon>,
};
